name: Qt-Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Building-Qt:
    runs-on: windows-latest
    steps:
    - name: Step 1 - Installing deps
      run: |
        choco upgrade chocolatey -y
        choco install git -y
        choco upgrade git -y
        choco install cmake -y
        choco upgrade cmake -y
        choco install ninja -y
        choco upgrade ninja -y
        choco install perl -y
        choco upgrade perl -y
        choco install python -y
        choco upgrade python -y
        choco install mingw -y
        choco upgrade mingw -y
        choco install llvm -y
        choco upgrade llvm -y
        refreshenv
    - name: Step 2 - Checking deps
      run: |
        choco --version
        git --version
        cmake --version
        ninja --version
        perl --version
        python --version
    - name: Step 3 - Cloning Git
      run: git clone git://code.qt.io/qt/qt5.git qt6
    - name: Step 4 - Configuring Git
      run: git checkout v6.5.0
      working-directory: qt6
    - name: Step 5 - Fetching sub-modules
      run: perl init-repository --module-subset=essential
      working-directory: qt6
    - name: Step 6 - Building Qt6.5.0
      run: | 
        mkdir qt6-build
        cd qt6-build
        ..\qt6\configure.bat -prefix ${{ github.workspace }}\Qt6.5.0
        cmake --build .
        cmake --install .
